# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblInput = QtWidgets.QLabel(self.centralwidget)
        self.lblInput.setGeometry(QtCore.QRect(80, 70, 250, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblInput.setFont(font)
        self.lblInput.setAlignment(QtCore.Qt.AlignCenter)
        self.lblInput.setObjectName("lblInput")
        self.inputTelNumber = QtWidgets.QLineEdit(self.centralwidget)
        self.inputTelNumber.setGeometry(QtCore.QRect(360, 70, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.inputTelNumber.setFont(font)
        self.inputTelNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.inputTelNumber.setObjectName("inputTelNumber")
        self.btnOptimizeInput = QtWidgets.QPushButton(self.centralwidget)
        self.btnOptimizeInput.setGeometry(QtCore.QRect(125, 500, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnOptimizeInput.setFont(font)
        self.btnOptimizeInput.setObjectName("btnOptimizeInput")
        self.btnCancelOptimization = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelOptimization.setGeometry(QtCore.QRect(525, 500, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnCancelOptimization.setFont(font)
        self.btnCancelOptimization.setObjectName("btnCancelOptimization")
        self.btnResetOptimization = QtWidgets.QPushButton(self.centralwidget)
        self.btnResetOptimization.setGeometry(QtCore.QRect(325, 500, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnResetOptimization.setFont(font)
        self.btnResetOptimization.setObjectName("btnResetOptimization")
        self.lblOutputTelNumber = QtWidgets.QLabel(self.centralwidget)
        self.lblOutputTelNumber.setGeometry(QtCore.QRect(360, 140, 300, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblOutputTelNumber.setFont(font)
        self.lblOutputTelNumber.setText("")
        self.lblOutputTelNumber.setObjectName("lblOutputTelNumber")
        self.lblOutput = QtWidgets.QLabel(self.centralwidget)
        self.lblOutput.setGeometry(QtCore.QRect(80, 140, 250, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblOutput.setFont(font)
        self.lblOutput.setAlignment(QtCore.Qt.AlignCenter)
        self.lblOutput.setObjectName("lblOutput")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Telefonnummer optimieren"))
        self.lblInput.setText(_translate("MainWindow", "Bitte Telefonnummer hier eintragen:"))
        self.btnOptimizeInput.setText(_translate("MainWindow", "Optimieren"))
        self.btnCancelOptimization.setText(_translate("MainWindow", "Abbrechen"))
        self.btnResetOptimization.setText(_translate("MainWindow", "Zurücksetzen"))
        self.lblOutput.setText(_translate("MainWindow", "Strukturierte Telefonnummer:"))
